### ISSUE TITLE
CDM Contribution Review WG - September 5th, 2023

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2308]
# CDM Contribution Review Working Group Minutes - Chair: Tom H

## Date
September 5th, 2023 - 10 am ET / 3 pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] For Project Expo Demos reach out to [marketing@finos.org](mailto:marketing@finos.org) or [eteri.dvalishvili@finos.org](mailto:eteri.dvalishvili@finos.org) if you would like to showcase your use case on November 1st at the [OSFF NY 2023](https://www.finos.org/hosted-events/2023-11-01-open-source-in-finance-forum-new-york).
- [x] Approve past meeting minutes
  - [x] https://github.com/finos/common-domain-model/issues/2289
- [x] New Project Boards
- [x] Tom H comment: I would like to discuss the changes made in PR [2292](https://github.com/finos/common-domain-model/pull/2292)
- [x] Acceptance of two maintainers - David Shone #2345 and Adrian Dale #2347
- [x] Enhancements to support ETD Transactions made in PR [2342](https://github.com/finos/common-domain-model/pull/2342)
- [x] Enhancements to support Commodity derivative product features in PR [2357](https://github.com/finos/common-domain-model/pull/2357)
- [x] Enhancements to support index name in PR [2336](https://github.com/finos/common-domain-model/pull/2336) and related design discussion
- [x] AOB, Q&A & Adjourn (5mins)

## Discussion points
- [x] JPM introduced themselves as a new participant.
- [x] There were no comments or objections to the prior meeting.
- [ ] Tom introduced new project boards for roadmaps. The TAs will work in add relevant work to the roadmaps available to the public. Dan suggested that the target completion dates for the TAs to update the roadmap. Tom commented that his intention is to update ICMA prior to FINOS event and we will keep this item open for review by the CRWG.
- [x] Tom introduced a new board for tracking CRWG open items and PR reviews. Some questions were raised around priorities and what is included. Tom noted that these items are from the Core CDM issues list. David raised a point that prioritization could be included in the operational procedures. David will add his comments and suggestions to issue #2129, Tom commented that at this time it's up to the contributors to move their PRs through the process by reaching out to maintainers for pre-review and adding issues to the CRWG agenda.
- [x] Two items included requests to add David Shone (now with ISDA) and Adrian Dale (ISLA) as maintainers. There were no objections. Eteri will add them to the group.
- [x] Three PRs were presented for review, #2342 , #2357 and #2336. Maintainers should review, comment and approve or suggest changes if necessary. 
- [x] Leo made note of the correct way to link issues to PRs so they are automatically closed when PRs are approved and merged.
- [x] None of the participants raise other business and the meeting was closed.

### Zoom info
Join Zoom Meeting
https://zoom.us/j/96436091087?pwd=TUZMYm1KdGt2YWtxdDVHY3BpQzh0QT09

Meeting ID: 964 3609 1087
Passcode: 238896

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by brianlynn2** [comment]
Brian Lynn / GEM & ISDA

**Comment by mgratacos** [comment]
Marc Gratacos / TradeHeader

**Comment by lolabeis** [comment]
Leo Labeis / REGnosys

**Comment by tabi5h** [comment]
Tabish Ahmed / ISDA

**Comment by mikealambert** [comment]
Mike Lambert - Broadridge

**Comment by manel-martos** [comment]
Manuel Martos / TradeHeader

**Comment by dschwartznyc** [comment]
daniel schwartz - FT Advisory

**Comment by dshoneisda** [comment]
David Shone/ISDA

**Comment by MarkNew-ISDA** [comment]
Mark New/ISDA

**Comment by rezagorjestani** [comment]
Reza Gorjestani/Standard Chartered Bank

**Comment by eacunaISDA** [comment]
Eleonora / ISDA

**Comment by rogerguitart** [comment]
Roger Guitart / TradeHeader

**Comment by eteridvalishvili** [comment]
Eteri / FINOS

**Comment by JanBaserba** [comment]
Jan Baserba / TradeHeader

**Comment by JBZ-Fragmos** [comment]
Jean-Baptiste ZIADE / Fragmos-Chain

**Comment by suyashyc** [comment]
Suyash Chaudhary /RBC

**Comment by jgavronsky** [comment]
Jane Gavronsky / FINOS

**Comment by rvincentISDA** [comment]
ruddy ISDA

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by eteridvalishvili** [comment]
@finos/cdm-maintainers, are we ready to approve this meeting and close the issue, or are there any action items that need to be carried forward to the next meeting? @tomhealey-icma

**Comment by eteridvalishvili** [comment]
Hi @tomhealey-icma Just following up to confirm if this issue can be marked as closed. Are there any outstanding action items that need to be addressed or carried over to the next contribution review working group?
