### ISSUE TITLE
CDM Steering Working Group - September 12, 2023

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2341]
# CDM Steering Working Group Minutes 
Meeting Host: David Shone, ISDA

## Date
September 12th, 2023 - 11am ET / 4pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x]  1.	Convene & Roll Call reminder- @eteridvalishvili 
- [x]  2.	Display FINOS Antitrust Policy Summary slide- @eteridvalishvili 
- [x]  3.	https://github.com/finos/common-domain-model/issues/2385 - @eteridvalishvili 
- [x]  4.	For Project Expo Demos reach out to [marketing@finos.org](mailto:marketing@finos.org) or [eteri.dvalishvili@finos.org](mailto:eteri.dvalishvili@finos.org) if you would like to showcase your use case on November 1st at the [OSFF NY 2023](https://www.finos.org/hosted-events/2023-11-01-open-source-in-finance-forum-new-york). @eteridvalishvili 
- [x]  5.	Review Action items from previous session- DShone
a.	None recorded in [#2243](https://github.com/finos/common-domain-model/issues/2243)
- [x]  6.	Roadmap Review
a.	Notification of any changes to delivery items or dates from prev agreed roadmap since last session ([roadmap.md](https://github.com/finos/common-domain-model/blob/master/ROADMAP.md))- Attendees
b.	Notification of any proposed new additions to roadmap (from any source)- Attendees
- [x]  7.	Governance & Operating Model topics
a.	Proposed standing agenda in absence of formal ToR- DShone
b.	Proposed updates to governance re: maintainer selection and appointment ([Proposed changes to Maintainer appointment and replacement rules · Issue #2379 · finos/common-domain-model (github.com)](https://github.com/finos/common-domain-model/issues/2379))- DShone
c.	Update on progress of proposed operating model & any decisions to be made by this group ([#2129](https://github.com/finos/common-domain-model/issues/2129)/[#2133](https://github.com/finos/common-domain-model/issues/2133))- @tomhealey-icma  (please confirm this is ok)
- [x]  8.	Release Schedule
a.	Proposal for Release Schedule ([#2056](https://github.com/finos/common-domain-model/pull/2056)) @chrisisla /@minesh-s-patel MPatel/CRayner (following discussion on 6th- let me know if the schedule proposal should be at next meeting)
- [ ]  9.	Other topics raised by community/other WGs-
a.	Serialisation- present proposal for support/dismissal by this group. Discussion ([#2180](https://github.com/finos/common-domain-model/discussions/2180)) @dschwartznyc 
b.	Change control guidelines- outline of proposals ([#2015](https://github.com/finos/common-domain-model/issues/2015#issuecomment-1636799319)) @brianlynn2 
i.	Then decision by steering group to either adopt proposals or appoint a detailed discussion in another WG or sub-group for representation to the steering group
c.	Proposal on CDM Reference Data Code List Management (#[2269](https://github.com/finos/common-domain-model/issues/2269)) @brianlynn2 
i.	Then decision by steering group to either adopt proposals or appoint a detailed discussion in another WG or sub-group for representation to the steering group
- [x]  10.	Confirm next meeting date & chair- DShone
a.	Propose monthly cadence- next regular will be 10th October
b.	Confirm need for any adhoc carry over of topics
- [x]  11.	AOB

## Minutes

** 6. Roadmap Review**
Notification of any changes to delivery items or dates from prev agreed roadmap since last session ([roadmap.md](https://github.com/finos/common-domain-model/blob/master/ROADMAP.md))- Attendees
Notification of any proposed new additions to roadmap (from any source)- Attendees\
- Steering WG forum is to inform of two critical points:
- Changes to planned roadmap deliveries (e.g., delays, re-baselining, removals).
- Proposed new additions.
- Most of the current roadmap is set out by the trade associations, who initially established the project but now other community members will contribute as well.
- Highlighted that ICMA would like to edit the Roadmap.md, but the changes he attempted were not committed. Roadmap.md should evolve into more of a timeline and needs regular updates to prevent staleness.

**Governance & Operating Model topics**
a. Proposed standing agenda in absence of formal ToR- DShone

- Agreed the set of topics is correct for this audience
- Suggestion that there should be flexibility in changing the agenda order based on relevant and urgent topics. This was agreed by the chair.

b. Proposed updates to governance re: maintainer selection and appointment ([Proposed changes to Maintainer appointment and replacement rules · Issue #2379 · finos/common-domain-model (github.com)](https://github.com/finos/common-domain-model/issues/2379))- DShone

- Suggested additions: Attendees should explicitly state if they represent their firms or themselves. Private individuals should be recorded as such.
- It's suggested that maintenance roles should be publicly visible.
- Change the wording to include that firms can change their rotation without a vote and cessation of maintainership so firms and private participants can rescind. 
- Discussion on whether there should be a limit on the number of maintainers to be added to the agenda for the next meeting.
- Reestablished we were going for 1 one vote per entity david to add that provision
- Agreed the wording and items proposed to be covered in this group- see initial powerpoint attached in Issue #2379- DShone to make changes and submit PR [[NOTE- subesequent request for FINOS to review- on hold]
- Additional considerations for next group ran through. 3 items to be added to the list- voting power, number of maintainers, tightening of skillset requirements. Group is to opine on issue by 29th Sept, with results to be presented at next steering group

c. Update on progress of proposed operating model & any decisions to be made by this group ([#2129](https://github.com/finos/common-domain-model/issues/2129)/[#2133](https://github.com/finos/common-domain-model/issues/2133))- [@tomhealey-icma](https://github.com/tomhealey-icma) (please confirm this is ok)

- SLA and operating model- two separate issues
- Tom Healey to provide an update on SLA and operating model. Issue #2129/#2133 is still open and needs review and commitment.

Serialisation- present proposal for support/dismissal by this group. Discussion ([#2180](https://github.com/finos/common-domain-model/discussions/2180)) [@dschwartznyc](https://github.com/dschwartznyc)

- Urgent need for CDM to define how information is shared and address the current gap. Clarification needed on interoperability goals. The CDM currently lacks a defined format for information exchange, which poses a challenge in various processes (e.g., settlement, reconciliation).
- JSON format is deemed insufficient and may hinder adoption due to its limitations in supporting embedded functions.
- Agreed that the TAWG sub-group should continue to look at this issue and present a formal proposal providing clarity on potential solution and resource commitment needed from sponsors/community
- Suggestion to include production implementers of the CDM. TAs agreed to invite

**8. Release Schedule**
- a. Proposal for Release Schedule ([#2056](https://github.com/finos/common-domain-model/pull/2056)) [@chrisisla](https://github.com/chrisisla) /[@minesh-s-patel](https://github.com/minesh-s-patel) MPatel/CRayner (following discussion on 6th- let me know if the schedule proposal should be at next meeting)
- Discussion on who should determine when a release is executed, and who is responsible for the associated tasks. Trust in technical skills is crucial. Consideration of additional tasks to open up the process. Group is invited to opine prior to 29 Sept

## Decisions Made

- The Roadmap.md should evolve into more of a timeline and needs to be regularly updated to prevent staleness.
- Future maintainers should explicitly state whether they represent their firms or themselves. Private individuals should be recorded as such. Maintainer roles should be made public on the GitHub repository. 
  - There will be a discussion in the next meeting about potentially adding a limit on the number of maintainers.
- Issue #2129/#2133 regarding the proposed operating model is still open and requires review and commitment.
- The proposal for a Release Schedule (#2056) will be discussed at the next meeting.
- Dan Schwartz will present more on the Serialization proposal for support/dismissal by the group.

## Action Items

- [ ] @finos/cdm-maintainers  to update Roadmap.md before the next Steering Working Group meeting.
- [ ] @finos/cdm-maintainers and all attendees. Consideration of additional changes for the next meeting: Founding tiers providing one maintainer, high consensus for removal of maintainers, notification periods, forced review of governance, and potential limits on the number of maintainers. Commentary on issue #2379 by 29th Sept @dshoneisda will make proposals
- [ ] @finos/cdm-maintainers and all attendees - Comments on ([#2129](https://github.com/finos/common-domain-model/issues/2129)/[#2133](https://github.com/finos/common-domain-model/issues/2133)) to be added by all attendees by the end of next week. David and Tom to create a final diagram for presentation at the next meeting.
- [ ] @dschwartznyc  to continue serialisation conversations with view to proposal for steering group in 4-6 weeks
- [ ] All attendees to generate questions on the release process by September 29th on issue:https://github.com/finos/common-domain-model/pull/2056 . Chris, Tom, and David to work through them.
- [ ] @dshoneisda  to carry on the following topics to the next meeting: 
     - b. Change control guidelines- outline of proposals ([#2015](https://github.com/finos/common-domainmodel/issues/2015#issuecomment-1636799319)) [@brianlynn2](https://github.com/brianlynn2)
     - i. Then decision by steering group to either adopt proposals or appoint a detailed discussion in another WG or sub-group for representation to the steering group
     - c. Proposal on CDM Reference Data Code List Management (#[2269](https://github.com/finos/common-domain-model/issues/2269)) [@brianlynn2](https://github.com/brianlynn2)
     - i. Then decision by steering group to either adopt proposals or appoint a detailed discussion in another WG or sub-group for representation to the steering group

### Zoom info
Join Zoom Meeting
https://zoom.us/j/98176867725?pwd=UFAxR0VMWTVJbDdOSkJycnBjMjZMZz09

Meeting ID: 981 7686 7725
Passcode: 740410
Find your local number: https://zoom.us/u/apsntFV0H

**Comment by dshoneisda** [comment]
For 5a. above Proposed standing agenda effectively setting out topic remit of the steering group

1.	Convene & Roll Call reminder
2.	Display FINOS Antitrust Policy Summary slide
3.	Review Action items from previous session
4.	Roadmap Review
a.	Notification of any changes to delivery dates from prev agreed roadmap since last session
b.	Notification of any proposed new additions to roadmap (from any source)
5.	Governance & Operating Model topics
a.	Update on any previously raised proposals related to this topic
b.	Presentation of any new proposals to change governance or operating model
6.	Release Schedule
a.	Notification of any changes to prev agreed release dates
b.	Presentation of any new proposals to change or manage release dates/process
7.	Other topics raised by community/other WGs
a.	Proposals from the community
8.	Confirm next meeting date & chair
a.	Include any ad-hoc interim meeting to complete topics
9.	AOB

**Comment by dschwartznyc** [comment]
Materials in support of item 7a (Serialization discussion)

[FINOS - CDM Serialization Call to Arms - Final.pdf](https://github.com/finos/common-domain-model/files/12579819/FINOS.-.CDM.Serialization.Call.to.Arms.-.Final.pdf)

**Comment by chrisisla** [comment]
Materials in support of item 6a (Release process)

[CDM_ReleaseProcess.pdf](https://github.com/finos/common-domain-model/files/12584631/CDM_ReleaseProcess.pdf)

**Comment by castrla** [comment]
Laurentino Castro - GS

**Comment by lolabeis** [comment]
Leo Labeis / REGnosys

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by dshoneisda** [comment]
David Shone/ISDA

**Comment by rvincentISDA** [comment]
Ruddy / ISDA

**Comment by brianlynn2** [comment]
Brian Lynn / GEM & ISDA

**Comment by mgratacos** [comment]
Marc Gratacos / TradeHeader

**Comment by dschwartznyc** [comment]
Dan Schwartz / FT Advisory

**Comment by JBZ-Fragmos** [comment]
JB Ziadé / FRAGMOS-CHAIN

**Comment by JBZ-Fragmos** [comment]
@dschwartznyc 

please make sure **Fragmos-Chain CTO**, namely Adrian Hutusoru is **definitly involved** in business rationale, use cases, validation process and any potential release, related to the **"Serialisation" project** (https://github.com/finos/common-domain-model/discussions/2180)

regards
JB

**Comment by dschwartznyc** [comment]
@JBZ-Fragmos as mentioned, Adrian is already an active part of the task force

**Comment by dshoneisda** [comment]
Updated powerpoint for governance changes with additional items for consideration added- voting power, skillset and numbers of maintainers:
[CDM_Maintainership Governance Proposals.pptx](https://github.com/finos/common-domain-model/files/12618311/CDM_Maintainership.Governance.Proposals.pptx)

**Comment by chrisisla** [comment]
Hi @dshoneisda,

For the final action point (follow on topics for the next meeting) I can confirm that both Issues have been picked up by the TAWG.

For the Reference Data Lists (#2269) the TAWG have created a separate task force to put together a recommendation on how to proceed. The recommendations will then be presented to the SWG.

For the Design Principles (#2015) Brian and I will first discuss the problem. It will then be presented at the next meeting of the TAWG so the group can decide a way forward. Once we have a proposal/recommendation it will be presented to the SWG.

So I think that the final action point can be set as completed, with the understanding that proposals for both topics will be presented back to the SWG in the following weeks. 

Thanks!
