### ISSUE TITLE
CDM Structured Products WG - September 12th

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2359]
# CDM Structured Products Working Group Minutes
Meeting Host: Jean-Baptiste Ziadé, Fragmos Chain 

## Date
September 12th, 2023 - 10am ET / 3pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] https://github.com/finos/common-domain-model/issues/2385 - @eteridvalishvili 
- [x] For Project Expo Demos reach out to [marketing@finos.org](mailto:marketing@finos.org) or [eteri.dvalishvili@finos.org](mailto:eteri.dvalishvili@finos.org) if you would like to showcase your use case on November 1st at the [OSFF NY 2023](https://www.finos.org/hosted-events/2023-11-01-open-source-in-finance-forum-new-york).
- [x] Approve past meeting minutes
      - https://github.com/finos/common-domain-model/issues/2242
- [x] Recap last year's achievements
- [x] Present the Roadmap draft
- [x] Q&A
- [x] Depending time we have, continue the gap analysis on the 7 term sheets received
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes

**Issue item: Recap of Last Year's Achievements:**

- Six main features in modeling were discussed:
  - Explicit representation of payout components in the product model.
  - Refactoring of price quantity to an observable base.
  - Introduction of the aggregation operator.
  - Refactoring of knock conditions.
  - Refactoring for cap and flow.
  - Introduction of multiplier/divisor object.
- Questions from Participants: Is this condition ready to be defined somewhere or not?
   - Interpretation rules were designed so as to be limited (ok with draft below)
   - then I believe also have reminded that each item would be described in usual CDM description field that exists in the model for such purpose 
   - also we may add that providing Documentation about the model is part of the Roadmap deliveries 
 - Are these new features specific to the structured product model aspect or added in the broader CDM?
    - @JBZ-Fragmos : They have been separated.

**Issue item: Continuation of Gap Analysis on Received Term Sheets:**

- Proposal to stop and continue as a homework assignment for the next meeting.
- @JBZ-Fragmos uses the visualization tool Rosett for sharing design proposals.
- Questions: Why was this particular term sheet selected? Does it represent high volume trading for such products?
   - Answer: It was chosen for specific modeling features, not necessarily high volume trading.

**Issue item: Roadmap 2023/24 for the Structured Product CDM Modeling:**

- Emphasis on the importance of validation and points for discussion.
- Suggestion for someone to take a step further in mapping the modeling with an internal high level.

## Action Items

- [x] If possible, @JBZ-Fragmos  to share resources for the recap of Last Year's Achievements item in the meeting issue for future reference.
- [x] RBC volunteered to work on the Gap analysis switch
  - [x] Gab analysis to be carried over to the next meeting
- [x] RBC volunteered to work on the roadmap 

### Zoom info
Join Zoom Meeting
https://zoom.us/j/92136087343?pwd=VER4aW83TC9HNDVxbXU3UUkxU1BoUT09

Meeting ID: 921 3608 7343
Passcode: 861434

**Comment by JBZ-Fragmos** [comment]
### ROADMAP 2023/24 for the Structured Product CDM Modelling
 
**MODEL REVIEW**
 
**A - Complete the gap analysis for the 7 Termsheets already provided by RBC – any additional Termsheets are still welcome**

- “gap analysis” consists in reviewing together the termsheets details during the work calls, highlight missing items in current CDM version and check that related problem statement is solved with the proposed new features designed in Fragmos Chain workspace
- who to perform it ? 
- what pace ?

**B - Get appropriate tools so that the group contributors might technically share the model items, which is an issue as of today**

- expected ultimate solution is to have a shared group workspace (who is in charge of such topic at FINOS/CDM/Regnosys ?)
- meanwhile (= short term), we could agree that hardcopies of Fragmos-Chain workspace would be done (by Regnosys ?) to be provided to core members, say on monthly basis for instance (by whom: Regnosys ?) so that each member wanting to get deeply involved may have its own copy of the reference workspace

 
 **C - Consider further challenging with mapping pieces of “script” if some members would agree to contribute to such exercise**
 = that means to share with the group actual pieces of script
 
 **D - Provide some documentation**

- Global design, foundational objects
- Focus on some interpretation rules (e.g. “branching logic”, etc.)
- Basic distribution, restricted to simple and common products (e.g. one Autocallable on Equity + one  Range Accrual on Rates) ; that is to illustrate how the model works with concrete examples
 
**MODEL RELEASE**
 
 **E - Create the GitHub Issues for items considered as prerequisite for Structured Group model, which **will have impact** accross the whole CDM model**
= required items not specific to Structured Products root, thus common to other types of products

-  Observable refactoring = Product Model + Event Model
- Knock refactoring
- Cap/Floor refactoring
- basic Enum list (e.g. DeterminationMethod, DateIsRelativeTo, PriceExpression, AggregationOperators)
- referencing mechanism refactoring (upgrade the functional behavior i.e. we want a “smart additive” behavior, instead of current “cancel/replace” effect

 
 **F - Create the GitHub Issues for each item of the Structured Group model (= required items **specific** to Structured root)**

- Product Model = **structuredPayout[*]** = new root attached to Payout
- Event Model = **tradeEconomicsObservation[*]** = new root attached to ObservationEvent

**Comment by rvincentISDA** [comment]
Ruddy / Finos

**Comment by mdemarzio** [comment]
Michelangelo de Marzio / ISDA

**Comment by dshoneisda** [comment]
David Shone/ISDA

**Comment by suyashyc** [comment]
Suyash Chaudhary / RBC

**Comment by JBZ-Fragmos** [comment]
**Recap of Last Year's Achievements:**

![image](https://github.com/finos/common-domain-model/assets/92978493/23d82479-c4c0-45e4-96e9-4b3ea7d41203)
