### ISSUE TITLE
CDM Technology Architecture Review WG - September 14th, 2023

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2360]
# CDM Technology Architecture Working Group Minutes
Meeting Host: Chris Rayner, ISLA

## Date
September 14th, 2023 - 9 am EST / 2 pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] https://github.com/finos/common-domain-model/issues/2385 - @eteridvalishvili
- [x] For Project Expo Demos reach out to [marketing@finos.org](mailto:marketing@finos.org) or [eteri.dvalishvili@finos.org](mailto:eteri.dvalishvili@finos.org) if you would like to showcase your use case on November 1st at the [OSFF NY 2023](https://www.finos.org/hosted-events/2023-11-01-open-source-in-finance-forum-new-york).
- [x] Approve past meeting minutes
  - [x] https://github.com/finos/common-domain-model/issues/2304
- [x] Updates
  - [x] Update on Serialisation (see discussion #2180 and SWG minutes #2341)
  - [x] Update on Versioning (see discussion #2305)
- [x] Discussion topics
  - [x] #2269
  - [x] (Moved to next meeting) #2015 
  - [x] Preliminary discussion on DSL enumerated list fixes
- [x] AOB, Q&A & Adjourn (5mins)

## Discussion points
**Reference Data**
- Solution needs to be independent of programming language
- APIs could have issues with access to internal or external lists
- Initial analysis shows small percentage (less than 20%) of lists used in model functionality 
- Proposed incremental approach to implementation
- Generally in favour of "dynamic" approach suggested in #2269
- Potential solution is new syntax i.e. new special extended list type, do not use existing "enum"
- Next step is to setup a task force (Tom, Minesh, Brian, Dan, Chris) to define recommendations to present to SWG

**Setting up a Task Force**
- Discussion on how we could setup initiative task forces in the future
- Jane suggested
  - CDM mailing list
  - FINOS can help setup a temporary mailing list for a project e.g. cdm-serialisation@finos.org
  - Can socialise on publications e.g. This week at FINOS, monthly newsletter, podcasts, info sessions
  - Can use github discussions or FINOS can help create a slack channel for the group

**DSL changes**
- Enumerated List representation
  - Change to fix DSL so it respects format of enumerated list values when serialising
  - Switch will be added so will have no impact now
  - Next major version (which expects breaking changes) will expect values to match the model
- New Function syntax
  - The ability to add constructors will be added to the DSL
  - These can be used in functions
  - Should reduce the size and complexity of the model

## Action Items
- [x] Additional comments on versioning to be added to the discussion #2305 - @dschwartznyc @tomhealey-icma 
- [x] Task force to be created to work on reference lists #2269 - @chrisisla 
- [x] Outstanding questions on DSL enumeration list values format change - @minesh-s-patel to chat to @tomhealey-icma 
- [x] Windows build issues - @minesh-s-patel to chat to @tomhealey-icma about Mao's suggestion of using a github action
- [x] Design Principles topic for next meeting to be socialised - @chrisisla to liaise with @brianlynn2 
- [x] Next meeting request REGnosys to present new DSL format - @hugohills-regnosys 

### Zoom info
Join Zoom Meeting
https://zoom.us/j/99036410403?pwd=MXNINndYcEd0dTBUZERuYTFwRGpWZz09

Meeting ID: 990 3641 0403
Passcode: 745379

**Comment by brianlynn2** [comment]
Brian Lynn / GEM & ISDA

**Comment by lolabeis** [comment]
Leo Labeis / REGnosys

**Comment by dshoneisda** [comment]
David Shone/ISDA

**Comment by AdrianJenksD2LT** [comment]
Adrian Jenks/D2 Legal Technology

**Comment by dschwartznyc** [comment]
dan schwartz/ft advisory

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by jgavronsky** [comment]
Jane / FINOS

**Comment by brooklynrob** [comment]
Rob Underwood / JP Morgan Chase / brooklynrob

**Comment by rezagorjestani** [comment]
Reza Gorjestani/Standard Chartered Bank

**Comment by minesh-s-patel** [comment]
@minesh-s-patel /REGnosys

**Comment by hugohills-regnosys** [comment]
Hugo Hills / REGnosys

**Comment by eacunaISDA** [comment]
Eleonora / ISDA
