### ISSUE TITLE
CDM Contribution Review Working Group - September 19th, 2023

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2361]
# CDM Contribution Review Working Group Minutes
Meeting Host: David Shone, ISDA

## Date
September 19th, 2023 - 10 am ET / 3 pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] https://github.com/finos/common-domain-model/issues/2385
- [x] For Project Expo Demos reach out to [marketing@finos.org](mailto:marketing@finos.org) or [eteri.dvalishvili@finos.org](mailto:eteri.dvalishvili@finos.org) if you would like to showcase your use case on November 1st at the [OSFF NY 2023](https://www.finos.org/hosted-events/2023-11-01-open-source-in-finance-forum-new-york).
- [x] Approve past meeting minutes
  - [x] https://github.com/finos/common-domain-model/issues/2308
- [x] Review of Top 5 Critical PRs and Status Updates
- [x] The deadline for final comments on [GitHub Issue #2133](https://github.com/finos/common-domain-model/issues/2133), addressing the steps required to ensure the prompt clearance of PRs and issues, is set for September 29th. Following this date, all feedback will be compiled and prepared for presentation at the Steering Working Group on October 19th, 2023.
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes

**Issue ([#2129](https://github.com/finos/common-domain-model/issues/2129)/[#2133](https://github.com/finos/common-domain-model/issues/2133))**
- The community has until the end of next week to comment on these 2 issues with thoughts on the process for reviewing PRs. @tomhealey-icma  and @dshoneisda will diagram and summarize it before the next Steering WG meeting.

**Review of items marked as critical:**

**https://github.com/finos/common-domain-model/pull/2391**
- Tom: The building on Windows is not working, and the PR is not ready yet.
- Has since been approved and merged.

**https://github.com/finos/common-domain-model/pull/2380**
- Participant was not present for this PR, so David commented and it has since been closed.

**https://github.com/finos/common-domain-model/pull/2200**
- Tom: Do these need to move to a new repo?
- They were rebuilt in the new structure when the structure was changed. Everything is under examples. Currently pending approval. 
- @chrisisla: Is the idea to move these out with the model?
- Dan: The test cases should stay with the production release examples that are just for people's reference. 
- David: Can I propose we merge it?
- Chris: Can we establish who will fix any issues it may cause?
- Tom: That would come back to us.

**Question on commodity delivery release development?** 
- @rvincentISDA: Approved it.

**https://github.com/finos/common-domain-model/pull/2153**
- Regnosys: The files have an ICMA copyright on it. Is this intended? 
- Tom: No, it indicates that the examples were created by ICMA. 
- Chris: Mao mentioned that participants can ignore the copyright and/or remove it. Because the Apache 2 license overrides the copyright.
- Tom to get feedback from ICMA legal on license and let FINOS know if there are any questions.

**https://github.com/finos/common-domain-model/pull/2153** 
- Tom has incorporated changes and it builds successfully.
- Chris: The closing functionality goes against best practice. Possible to ubstitute as part of the actual contractual details.
- Leo: Generally not closed but depends on how you want to define it. 
- Tom: Come up with an action plan. We're missing a definition and a policy around the use of that capability. 

**https://github.com/finos/common-domain-model/pull/2056**
- This will be brought to the steering working group next month for finalization.

**David: Ruddy, what is the result of[ https://github.com/finos/common-domain-model/pull/2217](https://github.com/finos/common-domain-model/pull/2217)**
- Ruddy: The contribution seems to be an issue with Github, where contributions end up in commits that are not related to it.
- Ruddy to follow up and connect with Regnosys and then follow up with the group.

## Decisions Made

Maintainers will work on defining a policy and establishing a clear definition around the use of a specific.

## Action Items

- [x] Everyone to review and comment on issues ([#2129](https://github.com/finos/common-domain-model/issues/2129)/[#2133](https://github.com/finos/common-domain-model/issues/2133)) and https://github.com/finos/common-domain-model/pull/2056
- [x] @tomhealey-icma to get feedback from ICMA legal on the license and let FINOS of any questions regarding it.
- [x] @tomhealey-icma to redo the pull request:https://github.com/finos/common-domain-model/pull/2153
- [x] @rvincentISDA to follow up and connect with Regnosys regarding the contribution issue on [PR #2217](https://github.com/finos/common-domain-model/pull/2217) and then update the group.

### Zoom info

Join Zoom Meeting
https://zoom.us/j/96436091087?pwd=TUZMYm1KdGt2YWtxdDVHY3BpQzh0QT09

Meeting ID: 964 3609 1087
Passcode: 238896
Find your local number: https://zoom.us/u/a3KWGNquN

**Comment by dshoneisda** [comment]
David Shone/ISDA

**Comment by jgavronsky** [comment]
Jane / FINOS

**Comment by mgratacos** [comment]
Marc Gratacos / TradeHeader

**Comment by rvincentISDA** [comment]
Ruddy / ISDA

**Comment by lolabeis** [comment]
Leo Labeis / REGnosys

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by Tciulla123** [comment]
Thomas Ciulla - Treliant

**Comment by eacunaISDA** [comment]
Eleonora / ISDA

**Comment by manel-martos** [comment]
Manuel Martos / Tradeheader
