### ISSUE TITLE
CDM Contribution Review Working Group - October 3rd, 2023 

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2405]
# CDM Contribution Review Working Group Minutes
Meeting Host: Chris Rayner, ISLA

## Date
October 3rd, 2023 - 10 am ET / 3 pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] For Project Expo Demos reach out to [marketing@finos.org](mailto:marketing@finos.org) or [eteri.dvalishvili@finos.org](mailto:eteri.dvalishvili@finos.org) if you would like to showcase your use case on November 1st at the [OSFF NY 2023](https://www.finos.org/hosted-events/2023-11-01-open-source-in-finance-forum-new-york).
- [x] Approve past meeting minutes
  - [x] https://github.com/finos/common-domain-model/issues/2361
- [x] Release proposal that is coming from DRR production users  (@dshoneisda ) 
- [x] Review Approved PRs
- [x] Review old Issues
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes

**Proposed Major Release**
- major release required for industry testing of DRR by mid october
- requested list of breaking changes to be provided as hard to wade through release notes
- agreement on future enhancements to make it easier to review release documentation between versions
- testing of releases queried - unit tests must complete successfully otherwise release fails
- there are other PRs that need to be included in this release
- there are outstanding issues that also need to be addressed in this release
- main breaking change is DSL updates
- REGnosys dependencies now moved into the DSL so will be open source
- DRR remains as open access - not open source (for now)

**Pull Requests**
- reviewed 3 PRs which will hopefully be able to be merged/closed
- see Action Items

**Open Issues**
- 83 Issues open at the moment
- Several can be converted to Discussions (thank you @lolabeis for doing this!)
- requested that people review their open issues and close if no longer relevant
- also please reach out to participants/maintainers if have questions or want to increase priority

## Action Items
- [x] Address conflict with Readme.md on #2160 and a Maintainer can then merge - @eteridvalishvili 
- [x] Comment on #2179 to see if still required - @chrisisla 
- [x] Update branch for #2401 and then approve so can be merged - @rvincentISDA @chrisisla 
- [x] Provide list of PRs/Issues that ISLA would like addressed in proposed Major release - @chrisisla 
- [x] Provide list of PRs/Issues that ICMA would like addressed in proposed Major release - @tomhealey-icma 
- [x] Decide on content of proposed Major release mid October - @dshoneisda @tomhealey-icma @chrisisla 
- [ ] Provide list of breaking changes for proposed Major release - @lolabeis / REGnosys
- [ ] Is there any additional regression testing done for Major releases - @lolabeis / REGnosys
- [x] Discuss options for adding legal agreement to product - @lolabeis @tomhealey-icma @rvincentISDA  and others when required

### Zoom info

Join Zoom Meeting
https://zoom.us/j/96436091087?pwd=TUZMYm1KdGt2YWtxdDVHY3BpQzh0QT09

Meeting ID: 964 3609 1087
Passcode: 238896
Find your local number: https://zoom.us/u/a3KWGNquN

**Comment by dshoneisda** [comment]
[CDM5.0 proposal.pptx](https://github.com/finos/common-domain-model/files/12791226/CDM5.0.proposal.pptx)

Material for point 3

**Comment by lolabeis** [comment]
Leo Labeis / REGnosys

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by dshoneisda** [comment]
David Shone/ISDA

**Comment by d-sen-gupta** [comment]
Dhruva / JPMC

**Comment by JBZ-Fragmos** [comment]
Jean-Baptiste Ziade / **Fragmos-Chain**

**Comment by tabi5h** [comment]
Tabish / ISDA

**Comment by eacunaISDA** [comment]
Eleonora / ISDA

**Comment by mgratacos** [comment]
Marc Gratacos / TradeHeader

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by rvincentISDA** [comment]
Ruddy / ISDA

**Comment by mikealambert** [comment]
Mike Lambert / Broadridge

**Comment by suyashyc** [comment]
Suyash Chaudhary / RBC

**Comment by lolabeis** [comment]
As just discussed during the meeting, these are the (formerly) issues that have been converted into discussions:
#2422
#2423
