### ISSUE TITLE
CDM Derivatives Products and Business Events Working Group - January 24th, 2024 

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2628]
# CDM Derivatives Products and Business Events Working Group Minutes 
Meeting Host: David Shone, ISDA

January 24th, 2024 - 11:30 am EST / 4:30 pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes (N/A)
- [x] Content for CDM 5.4, planned release end of week- Leo Labeis, REGnosys
  - **Minor model change**
  - [x] #2639: PTRR Service Provider, Manu Carrera, TradeHeader
  - [x] #2647: Execution function to include lot identifier, Nick Moger, JPM
  - **Mapping/Fix**
  - [x] #2643: Price mappings for Known Amount Schedule, Gerard Opazo, TradeHeader
  - [x] #2593: ZC Qualification update, Marc Gratacos, TradeHeader
- [x] Option Payout Refactoring Proposal- Roger Guitart, TradeHeader- [https://github.com/finos/common-domain-model/issues/2624](https://protect-usb.mimecast.com/s/rFz4C1Vv2GIrvWBlULA2U4?domain=github.com)  
[ISDA Common Domain Model - DBPE- 20240124.pdf](https://github.com/finos/common-domain-model/files/14036921/ISDA.Common.Domain.Model.-.DBPE-.20240124.pdf)

- [x] FixedRateCompounding- JB Ziade, Fragmos Chain, [https://github.com/finos/common-domain-model/issues/2098](https://protect-usb.mimecast.com/s/ahIUC3Yx4yUjLNo3tgQdtJ?domain=github.com) [ISDA Common Domain Model - DPBE- 20231206.pdf](https://github.com/finos/common-domain-model/files/14039622/ISDA.Common.Domain.Model.-.DPBE-.20231206.pdf)
- [x] Intermediate principal payments- JB Ziade, Fragmos Chain, [https://github.com/finos/common-domain-model/issues/2163](https://protect-usb.mimecast.com/s/9cqkC4Wy5zUZLkEPsx-d1l?domain=github.com) [ISDA Common Domain Model - DPBE- 20231206.pdf](https://github.com/finos/common-domain-model/files/14039622/ISDA.Common.Domain.Model.-.DPBE-.20231206.pdf)
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes-  

Intro

- DS welcomed everyone to new group; re-iterated use of new mailing lists for those interested in this group
- DS alerted attendees that next session would be 31st Jan with the cadence thereafter being fortnightly
- DS asked that attendees submit items for the agenda to him prior to the next session
- DS asked presenters to be aware that some attendees may be dialled in or unable to use all features so visual material should be loaded/referenced on agenda, and presenters should take care to keep audience aware of where they are in the deck/the issue they have

5.4 Content
- All 4 items were subject to clarification questions from attendees, but ultimately approved for release in 5.4 Leo Labeis to coordinate release for Friday 26th

Option Payout refactoring
-	Support for proposal from attendees
-	Roger to complete conversations with those commenting on the issue and bottom out conversations
-	Roger to review all validation rules to ensure re-factoring does not break them
-	Once complete Roger can bring to a future DPBE for final approval

FixedRateCompounding
-	Proposal accepted by group
-	JB Ziade to create PR to be reviewed by maintainers

Principal Amount
-	REGnosys, Tokenovate and others proposed that rather than remove the validation altogether that a more conditional based approach was taken to avoid removing useful validation where required
-	DS to convene REGnosys/Fragmos discussion to consider options

### Zoom info
Join Zoom Meeting
https://zoom.us/j/94131415778?pwd=L1A2aUhoTEhoODdUZ0lrUkNLOXBiQT09
Meeting ID: 941 3141 5778
Passcode: 189607

Find your local number: https://zoom.us/u/adEnPA6h80

**Comment by lolabeis** [comment]
Leo Labeis / REGnosys

**Comment by Oblongs** [comment]
Lionel Smith-Gordon / REGnosys

**Comment by rogerguitart** [comment]
Roger Guitart / TradeHeader

**Comment by JBZ-Fragmos** [comment]
Jean-Baptiste Ziade - FRAGMOS CHAIN

**Comment by eteridvalishvili** [comment]
Eteri / FINOS

**Comment by eelramy92** [comment]
Elias EL RAMY / Societe Generale

**Comment by deyan-paroushev** [comment]
Deyan Paroushev / Sofia University St Kliment Ohridski

**Comment by dshoneisda** [comment]
David Shone/ISDA

**Comment by nicholas-moger** [comment]
Nick Moger JP Morgan

**Comment by manucarreramoreno** [comment]
Manuel Carrera / Tradeheader

**Comment by manel-martos** [comment]
Manuel Martos / Tradeheader

**Comment by dschwartznyc** [comment]
Dan Schwartz / FT Advisory

**Comment by sashworthTKN** [comment]
stephen ashworth/Tokenovate
