### ISSUE TITLE
CDM Derivatives Products and Business Events Working Group - February 27th, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2669]
# CDM Derivatives Products and Business Events Working Group Minutes 
Meeting Host: David Shone, ISDA

February 27th, 2024 - 11:30 am EST / 4:30 pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes (N/A)
   - [x] https://github.com/finos/common-domain-model/issues/2666
 - [x] Next planned CDM minor release (`CDM 5.6`)
   - [x] Proposed release date: ASAP (possibly by Tues 27/2 COB if no impediment)
   - [x] Content to be ratified:
     - [x] Master Agreement type #2696 
     - [x] Qualification fix for ETD underlier #2705 
   - [x] Mapping or bugfix update (no model change):
     - [x] SettlementType mapping fixes #2701
     - [x] Commodity Classification mapping fixes: #2715 
     - [x] DSL bugfix for handling null value: #2729 
   - [x] Content already approved at previous DPBE:
     - [x] Commodity Forward qualification #2719 
     - [x] Day count fraction enum #2711 
- [x] Commodity Physical Options - #2723 @manucarreramoreno 
[commodityPhysicalOptions.pptx](https://github.com/finos/common-domain-model/files/14417503/commodityPhysicalOptions.pptx)
- [x] Updates to questions asked on Swap proposal from previous DPBE #2745 - @JBZ-Fragmos 
[Price Return Swap v3.pptx](https://github.com/finos/common-domain-model/files/14417521/Price.Return.Swap.v3.pptx)
- [ ] Initial proposals to model Accumulators/DeAccumulators #2746 - Fragmos/JPM/Pictet- @JBZ-Fragmos 
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes-  

Meeting Administration

-	ED ran through meeting notices and anit-trust statement
-	DS ran through previous minutes and actions which were approved

Next planned CDM minor release- 5.6

-	All items listed in the agenda were presented and approved for release on 27th Feb and were released that evening

Commodity Physical Options

-	MC ran through the proposals in the powerpoint embedded in the agenda
-	There was debate on whether the settlement property under discussion should sit at the option product level or the underlying commodity level.
-	3 types of commodity option
o	Financial Options: commodity underlier and settlement type = cash
o	Physical Options: commodity underlier and settlement type = physical
o	Commodity Swaption: settlement type = physical but underlier is contractual product = commodity 
-	**Action**: MC to write up 3 options and run past Harry McAllister
-	Subsequenty it has been confirmed that HMc agreed to the above approach and MC has proceeded with the contribution

Updates to questions asked on Swap Proposals from previous DPBE

-	JB ran through answers to previously raised questions- see presentation in agenda
-	No further feedback/questions raised on the call
-	**Action:** JB to raise a PR, separating out swap from accumulators, to represent changes
-	Subsequently, the PR has raised further questions/changes to deal with backward compatibility. JB will present updated/revised proposal at DPBE on 13th March

Initial proposals to model accumulators/deaccumulators

-	JB ran quickly through proposals for these products; ran out of time for any questions on the call
-	**Action**: attendees to provide feedback to JB on the proposals
-	**Action**: JB to update proposals based on feedback received to re-present at DPBE on 13th March

### Zoom info
Join Zoom Meeting
https://zoom.us/j/94131415778?pwd=L1A2aUhoTEhoODdUZ0lrUkNLOXBiQT09
Meeting ID: 941 3141 5778
Passcode: 189607

Find your local number: https://zoom.us/u/adEnPA6h80

**Comment by dshoneisda** [comment]
David Shone/ISDA

**Comment by Oblongs** [comment]
Lionel Smith-Gordon for REGnosys

**Comment by manucarreramoreno** [comment]
Manuel Carrera / Tradeheader

**Comment by JBZ-Fragmos** [comment]
Jean-Baptiste Ziadé   /  FRAGMOS-CHAIN

**Comment by rogerguitart** [comment]
Roger Guitart / TradeHeader

**Comment by tzurcher** [comment]
Timothée Zürcher / Pictet

**Comment by ebataller** [comment]
Eric Bataller / Tradeheader

**Comment by deyan-paroushev** [comment]
Deyan Paroushev / Sofia University St Kliment Ohridski

**Comment by manel-martos** [comment]
Manuel Martos / Tradeheader

**Comment by eacunaISDA** [comment]
Eleonora / ISDA

**Comment by hugohills-regnosys** [comment]
Hugo Hills / REGnosys
