### ISSUE TITLE
CDM Structured Products WG - July 9th, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#2952]
# CDM Structured Products Working Group Minutes
Meeting Host: Jean-Baptiste Ziadé, Fragmos Chain 

## Date
July 9th, 2024 - 10 am ET / 3 pm BST

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
  - [x] https://github.com/finos/common-domain-model/issues/2902
- [x] https://github.com/finos/common-domain-model/issues/2941
- [x] AOB, Q&A & Adjourn (5mins)

**Materials** 

## Minutes

- FRAGMOS : presentation to attendees, based on Rosetta graphical view of Fragmos WS “BespokePayoutFormula” (summary : would extend CDM type model with a backward-compatible set of components, which permits to optionally describe any payout formula at granular/calculable level based on human-&-machine readable design)
   - WS view access : link PR #2962
   - Description : link GitHub Issue #2941
   - As an information, other presentations of the model proposal were made prior to the meeting to some participants i.e. GOLDMAN SACHS + BLOOMBERG + SOCIETE GENERALE
- RBC : request FRAGMOS to add sample of termsheets with corresponding trade file using BespokePayoutFormula, inside GitHub Issue #2941 (e.g. Autocallable, Range Accrual, Steepener, Options, etc.)
- SG : request FRAGMOS to elaborate on potential re-use of “BespokePayoutFormula” as part of lifecycle event (cautious of time, FRAGMOS answered such topic would be addressed in future WG meeting)

 
## Action Items

- [ ] FRAGMOS to add sample of termsheets with corresponding trade file using BespokePayoutFormula, inside GitHub Issue #2941
- [ ] FRAGMOS to start drafting description of the “BespokePayoutFormula” in PPT Deck (material required to prepare presentation to CRWG looking forward to Production release)
- [ ] ALL PARTICIPANTS :
   - [ ] to review trade file samples in Issue #2941
   - [ ] to review model in PR #2962
   - [ ] to raise any feedback/suggestions/questions to FRAGMOS on ad hoc basis (no need to wait for next WG meeting, please contact directly FRAGMOS as need be, any intermediary interaction between participants is helpful to prepare next meetings)

### Zoom info
Join Zoom Meeting
https://zoom.us/j/92136087343?pwd=VER4aW83TC9HNDVxbXU3UUkxU1BoUT09

Meeting ID: 921 3608 7343
Passcode: 861434
Find your local number: https://zoom.us/u/ad5NMLeH9R

**Comment by JBZ-Fragmos** [comment]
JB Ziade - FRAGMOS

**Comment by refset** [comment]
[Jeremy Taylor](https://www.linkedin.com/in/jdtaylor/) - [JUXT](https://www.juxt.pro/)

**Comment by eelramy** [comment]
Elias El Ramy / Société Générale
