### ISSUE TITLE
CDM Steering Working Group - August 14th, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#3076]
# CDM Steering Working Group Minutes 
Meeting Host: David Shone, ISDA

## Date
August 14th, 2024  - 11am ET / 4pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & Roll Call reminder- @eteridvalishvili 
- [x]  Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) @eteridvalishvili 
- [x]  Approve past meeting minutes
  - [x] https://github.com/finos/common-domain-model/issues/3024
- [x] Release schedule, guidelines & PR approval- documentation confirmation and final agreement on PR approvals [@brianlynn2](https://github.com/brianlynn2 [10 min]
- [x] Release Manager/Documentation resources update-[@dshoneisda](https://github.com/dshoneisda) [3min]
- [x] Serialisation update- @chrisisla  [3min]
- [x] Asset Refactoring Taskforce update [@lolabeis](https://github.com/Oblongs) [10 min]
- [x] Prioritisation of future items- community involvement - discussion [@dshoneisda](https://github.com/dshoneisda) [10 min]
- [x] Review [2024 CDM Roadmap](https://cdm.finos.org/docs/cdm-overview#cdm-2024-roadmap) - @dshoneisda and @eteridvalishvili [5 min]
- [x] AOB

## Minutes

- Meeting admin completed
- From previous minutes:
   - There was no further info from ICMA on the discussion started re: content scope discussion #2979 and this has now been closed
   - @dshoneisda explained a list had been started but he had not had time to publish the poll promised for future work prioritisation, this action is rolled, and negates the item on the agenda to discuss prioritisation of future items

**Release material:** @brianlynn2 confirmed final scheduling guidelines and PR approval rules have been agreed and published to roadmap.md, governance.md and also the FINOS CDM website. The vidoe from previous SWG has also been published to the CDM materials page here: [CDM Materials](https://url.usb.m.mimecastprotect.com/s/J3HKCxorP2Tp0JrBHvhWuyGvC2?domain=deploy-preview-3091--finos-cdm.netlify.app).

**Release manager/documentation resource** @dshoneisda noted that ISDA are in process of agreeing a contract to implement the Release Manager role executing on the guidelines and process agreed in previous agenda item. Documentation resource will also be sought

**Serialisation**  @chrisisla noted that ISLA are in contract negotiations to deliver the first phase of Serialisation (agreed back in Nov/Dec 2023) with work due to begin in September. ICMA requested review of contract prior to signing, which was politely refused. The delivery plan and proposed delivery will still be presented at the TAWG so the community can have visibility of what is being delivered.

**ART** @dshoneisda gave a brief update that Phase 2 has been released, and Phase 3 is under review. Delivery and completion is now likely to be early September

**Roadmap** @dshoneisda and @eteridvalishvili noted that the CDM roadmap is due for update by WG chairs. @eteridvalishvili circulated a sheet for chairs to update: [2024 Roadmap](https://url.usb.m.mimecastprotect.com/s/K3kMCoAgDjfAGDrOt1fwupEpma?domain=docs.google.com).

- there was no other business to discuss

### Zoom info

Join Zoom Meeting
https://zoom.us/j/93756205037?pwd=NFd1SUh1ZXdOdVNjQXdLVzZBbnpudz09
Meeting ID: 937 5620 5037
Passcode: 911071

Find your local number: https://zoom.us/u/axu5kFLKy

**Comment by dshoneisda** [comment]
David Shone/ISDA

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by brianlynn2** [comment]
Brian Lynn / ISDA, GEM
