### ISSUE TITLE
CDM Technology Architecture WG - September 12th, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#3119]
# CDM Technology Architecture Working Group Minutes
Meeting Host: Chris Rayner, ISLA

## Date
September 12th, 2023 - 9 am EST / 2 pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Review minutes of last meeting
   - [x] https://github.com/finos/common-domain-model/issues/3025
- [x] Updates (15 mins) 
  - [x] Rune issues #3046 - @chrisisla 
  - [x] Code Generators #2928 - @chrisisla 
  - [x] Serialisation - @chrisisla
  - [x] Ongoing Priorities Survey #3106 - @chrisisla
  - [x] Rune Translate2 - @davidalk
- [x] Rune language enhancements (10 mins) - @davidalk
- [x] TAWG Priority setting POSTPONED DUE TO TIME - @chrisisla
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes &  Discussion points

**Update on Rune Translate2**
- evolve translate syntax, more obvious mapping
- on the 3rd iteration of syntax
- focused on Party, then movinig onto Product mapping for testing
- aim is to have something ready by end of the year
- will need to migrate existing Translate synonyms to new Translate
- Hope to automate the process
_Questions_
- as CDM evolves will new mapping be required?
  - No
- is this a change to Rune syntax with unit tests in Rune?
- what will the impact on Python Code Generator be?
  - same testing process for new translate as for the original
  - first iteration is java, Translate 2 is open so hope others will help with Python
- will we need to replace mappers too?
  - can replace but not forced to

**Rune language enhancements**
Goal is to help make the Rune syntax more concise

_switch_
- replaces if/then, Rosetta will context validation checking
- needs to be supported by Python 
_Questions_
- can the output be a complex expression?
  - yes, and it will be one condition one output
- what are the "VALUES" allowed to be?
  - right now just eumerations, but support fore literals in future e.g. string, number
_TAWG Consensus_
- No issues raised
- Although has impact on Python this is not an issue
- **Conclusion:** change can be used in CDM prod and dev

_aliases_
- allow namespaces to be aliased
- so can import a namespace into an alias
_Questions_
- does Rune confirm no clash on the alias? i.e if you import to the same alias?
  - can import to same alias but must resolve otherwise get unresolved reference error
  can have multiple implorts into one alias
- When will this be available?
  - available now, hoping to go into CDM prod/dev imminently
_TAWG Consensus_
- No issues raised
- Queries on importing multiple namespaces to the same alias but no concerns
- **Conclusion:** change can be used in CDM prod and dev

_enums_
- simplify the syntax of conditional expressions
- modeller can omit the enum name as inferred by the type
_Questions_
- not as clear to read if the enum name has gone
  - there is a trade off between compactness and readibility
- having the enum name in the expression can make it harder to determine the logic. Can we do the same thing elsewhere?
  - yes, but could not think of any other area where this might be useful
  - modelling in rosetta the enumerations will appear making modelling easier
  - suggestion - add a tooltip over the enum value to show the enum name
_TAWG Consensus_
- No issues raised
- **Conclusion:** change can be used in CDM prod and dev

_extend enum_
- this is a future enhancement just being discussed now
- please provide feedback on the Rune Issue in the Agenda
_Questions_
- is this functionality supported in other languages like Java/Python?
  - not really, this is the concept of a superset/union 
  - we will need to support it in the generated code

 
## Action Items

- [x] Close the Rune Issues discussion #3119 - @chrisisla
- [x] Attendees to add comments to the enum Issue on the Rune repository rune-dsl#818
- [x] Add to Next Meeting Agenda - @chrisisla 
  - [x] Update on Serialisation, hopefully presenting the design
  - [x] If time pick up TAWG priority setting dropped off agenda for today #2919

### Zoom info
Join Zoom Meeting
https://zoom.us/j/99036410403?pwd=MXNINndYcEd0dTBUZERuYTFwRGpWZz09

Meeting ID: 990 3641 0403
Passcode: 745379
Find your local number: https://zoom.us/u/adtpQBjgT9

**Comment by SimonCockx** [comment]
Items for the agenda:
- Support for a switch operation: https://github.com/finos/rune-dsl/issues/819
- Shorthand for referencing enum values: https://github.com/finos/rune-dsl/issues/820
- Support import aliases to prevent name clashes: https://github.com/finos/rune-dsl/issues/821
- Point of discussion - proper support for enum extensions: https://github.com/finos/rune-dsl/issues/818

**Comment by mgratacos** [comment]
Marc Gratacos / TradeHeader

**Comment by manel-martos** [comment]
Manuel Martos / TradeHeader

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by dschwartznyc** [comment]
Daniel Schwartz/FT Advisory
