### ISSUE TITLE
CDM Contribution Review Working Group - November 5th, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#3209]
# CDM Contribution Review Working Group Minutes
Meeting Host: Chris Rayner, ISLA

## Date
November 5th, 2024 - 10 am EST / 3 pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
  - [x] https://github.com/finos/common-domain-model/issues/3167
- [x] TradeHeader
  - [x] https://github.com/finos/common-domain-model/issues/3194 -> new function Create_CancelledWorkflowStep
  - [x] https://github.com/finos/common-domain-model/pull/3197 and https://github.com/finos/common-domain-model/pull/3198 -> new CapacityEnum
  - [x] https://github.com/finos/common-domain-model/pull/3204 -> Java mapper update for FpML to CDM ingestion
- [x] AOB, Q&A & Adjourn (5mins)
  - [x] 2025 CDM Showcase - Call for Proposals

## Minutes

Previous minutes were accepted

_Discussion on CRWG and DPBE_
- Side discussion started on what DPBE should actually cover
- Was originally ported from ISDA WG so derivatives focused
- Not clear whether it is "Derivatives Products" and "[All] Business Events" or "[Derivative] Business Events"
- Suggestion that the WG could be expanded to be a general modelling WG i.e. cross domain
- Chris will bring to the SWG for further discussion

_Discussion on #3194_
- Requirement is to Cancel a workflowstep that has been accepted incorrectly
- DRR needs to report this as an error
- May need to differentiate between an Accepted and a Rejected workflowstep
- Chris will review and liaise with TradeHeader

_Discussion on #3197_
- General agreement need to adhere to ISO
- Also need a way to prevent CDM having to always include ISO lists as enum
- TAWG has already proposed how to do this
- Joule not in FpML Price Quote Unit Scheme, do we need it?

_Discussion on #3204_
- Quite a lot of discussion on whether should convert data as it comes into the CDM
- In this case the code being updated is an FpML mapper i.e. not core CDM, maps FpML to CDM
- Thus, as there would be no changes to core CDM, this should not be an issue
- In general the mapper assumes FpML prices are numeric values and not percentages
- Needs final review by Lyteck but general consensus was this should be okay

## Action Points 
- [x] Define scope of DPBE and CRWG - @chrisisla
- [x] Review Cancel Workflowstep Issue #3194 - @chrisisla
- [x] Georgina will confirm internally about use of Joule for #3197 - @gtarres
- [x] Review FpML mapper to ensure no impact on CDM and functionally correct for #3204 - @llynhiavu

## Zoom info

Join Zoom Meeting

https://zoom.us/j/96436091087?pwd=TUZMYm1KdGt2YWtxdDVHY3BpQzh0QT09
Meeting ID: 964 3609 1087
Passcode: 238896

Find your local number: https://zoom.us/u/a3KWGNquN

**Comment by gtarres** [comment]
Georgina / Tradeheader

**Comment by iansloyan** [comment]
Ian Sloyan - Finos

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA
