### ISSUE TITLE
CDM Steering Working Group - November 12th, 2024 

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#3211]
# CDM Steering Working Group Minutes 
Meeting Host: David Shone, ISDA

## Date
November 12th, 2024  - 10am ET / 3pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x]  Convene & Roll Call reminder- @eteridvalishvili 
- [x]  Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) @eteridvalishvili 
- [x]  Review Meeting Notices (see above)
- [x]  Approve past meeting minutes
  - [x] https://github.com/finos/common-domain-model/issues/3166
- [ ] Topics
  - [x] Define scope of CRWG and DPBE (see #3209) - @chrisisla 
  - [x] Notification of presentation of Serialization Design at TAWG on 14th November (see #3212)- @chrisisla
  - [x] CDM 6.0 update @lolabeis/@Oblongs 
   - [ARTForce SWG 12Nov24.pptx](https://github.com/user-attachments/files/17719849/ARTForce.SWG.12Nov24.pptx)
  - [x] Results of Chair nominations- https://github.com/finos/common-domain-model/issues/3187- @dshoneisda 
  - [x] Proposals on Chair governance going forward- @dshoneisda @tomhealey-icma 
- [ ] AOB

## Minutes

- **Define scope of CRWG and DPBE** (see CDM Contribution Review Working Group - November 5th, 2024 #3209) - @chrisisla
  - Discussion on the overlap in roles between the CRWG and DPBE.
  - Proposal to rename the DPBE to "Products and Business Events Working Group" to better reflect its broader scope.
  - Agreement on the need for a clearer distinction between functional approval and code review.
  - The importance of the CRWG's role in reviewing contributions and making sure there is alignment with design principles was emphasized.

- **Notification of presentation of Serialization Design at TAWG on 14th November** (see CDM Technology Architecture WG - November 14th, 2024 #3212) - @chrisisla
  - Chris presented the new serialization design.
  - Encouragement of community feedback on the design through the GitHub issue: https://github.com/finos/common-domain-model/issues/3236.
  - Planning for final approval of the design at the December 5th TAWG meeting.

- **CDM 6.0 update** @lolabeis/@Oblongs
  - Discussion on the timing of the release, considering necessary fixes and compatibility with Python implementations.
  - Decision to delay the release to later in December in order to include the Python implementation.

- **Results of Chair nominations** - Chair of SWG #3187 - @dshoneisda
  - David nominated and elected as the chair for the next term.
  - Discussion on formalizing the chair election process, including term limits and eligibility criteria.

- **AOB - Meeting Scheduling**
  - Agreement to schedule the CRWG and DPBE meetings on alternate weeks to avoid conflicts.

## Action Items

- **@dshoneisda**:
   - [x]  Reiterate the proposed scopes for the CRWG and DPBE based on existing governance.
   - [x]  Send out PR approval process guidelines.
   - [x]  Encourage maintainers to call out instances of non-adherence to the PR approval process.
   - [x]  Formalize the chair election process which includes term limits and eligibility criteria.

- **@chrisisla**:
   - [x]  Present the serialization design at TAWG on Dec 5th.
   - [x]  Encourage community feedback on the design in the https://github.com/finos/common-domain-model/issues/3236 issue.

- **@eteridvalishvili**:
   - [x]  Adjust meeting schedules for the CRWG and DPBE so they alternate for December and all of 2025.

- **@Oblongs**:
   - [ ]  Share the status update on CDM release with the wider community.

- **@finos/cdm-maintainers **:
   - [ ]  Everyone to share thoughts on the 2025 roadmap with @eteridvalishvili so she can compile together for discussion and presentation at the December's Steering WG. 

### Zoom info

Join Zoom Meeting
https://zoom.us/j/93756205037?pwd=NFd1SUh1ZXdOdVNjQXdLVzZBbnpudz09
Meeting ID: 937 5620 5037
Passcode: 911071

Find your local number: https://zoom.us/u/axu5kFLKy

**Comment by DIVA291265** [comment]
Daniel Ivanier, Fragmos Chain

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by cdmflow** [comment]
Dan Schwartz / FT Advisory

**Comment by nicholas-moger** [comment]
Nick Moger / JPM

**Comment by Oblongs** [comment]
Lionel Smith-Gordon / REGnosys

**Comment by lolabeis** [comment]
Leo Labeis / REGnosys (sorry for joining late)

**Comment by chrisisla** [comment]
I have added a discussion on the CRWG and DPBE topic: #3254

Please can everyone add any thoughts so we can review and action (if required) at the next SWG
