### ISSUE TITLE
CDM Technology Architecture Working Group - December 5th, 2024

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/common-domain-model#3219]
# CDM Technology Architecture Working Group Minutes
Meeting Host: Chris Rayner, ISLA

## Date
December 5th, 2024 - 9 am ET / 2 pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
  - [x] #3212 
- [x] Topics
  - [x] Serialization Design ratification - #3236 
  - [x] Review of 2024 & 2025 Roadmap
- [x] AOB
  - [x]  TAWG Chair

## Minutes &  Discussion points

**Discussion on Serialisation**
- Brian asked some questions on versioning but was generally happy with the spec
- Also suggested process flow and validation could have been explored more in the doc
- Minesh confirmed that the first phase was to get the format done first
- Then we can enhance to tighter validation etc. 
- There were no objections so the Serialization Specification has been formally accepted

**2024 Initiatives**
- Chris ran through the topics the TAWG had reviewed over the year, being:
  - Serialisation
  - Reference Data
  - Rune Extended Enums & Type Extension
  - Python version of CDM available under pip
  - Code Generators
  - CDM Survey (SWG)
    - 1. Translate open sourcing
    - 2. CDM Implementation examples
    - 3. Error Handling
    - 4. Serialisation phases 2/3
    - 5. Regression Testing
  - Github Actions
  - Choice operator
  - TAWG Remit
  - TAWG Vision Statement
  - TAWG Initiatives Roadmap for 2024
    - 1. Serialisation
    - 2. Reference Data
    - 3. Release Process (became Github Actions)
- Chris stated that as a group the TAWG had achieved a lot this year, which was echoed by the participants

**2025 Roadmap**
- Chris highlighted the items that were left over from the 2024 Roadmap, being:
  - Versioning
  - Interoperability
  - Change Control
  - Testing
  - Standard Error Handling
  - Native Functions
- Chris confirmed the TAWG will continue to review Rune and CDM technical changes
- Brian suggested that improved testing should be a priority:
  - Improved regression testing, maybe a broader scope too
  - Provide test cases between/across versions
- Dan agreed with this and suggested other testing types:
 - Provide a similar test pack for all code generators, more consistent testing
 - Confirm all language versions of CDM work expected (i.e. Java/Python consistent)
 - Cross language testing, perhaps written in Rune so language agnostic
- Dan also suggested that we need a clear definition of how to support native functions
- Marc said TradeHeader are looking to contribute more test cases and JSON samples
  - We should define a policy/governance for when firms want to add new functions to CDM
  - This should define the testing requirements
  - Plus define what artefacts are required for a contribution
  - The contribution and ongoing maintainance of CDM JSON samples needs to be defined too
- Minesh stated there will be further Rune contributions in 2025 
- He also agreed that testing could be improved:
  - More native CDM JSON test cases (i.e. not derived from FpML) would be good
  - Also need to way to better maintain these 
 
## Action Items

- [x] Create election of new TAWG chair issue - @chrisisla - #3292 
- [x] Update Serialization Specification issue to state accepted and close it - @chrisisla
- [x] Review the list of 2024 priorities from #2741 - Everyone

### Zoom info
Join Zoom Meeting
https://zoom.us/j/99036410403?pwd=MXNINndYcEd0dTBUZERuYTFwRGpWZz09

Meeting ID: 990 3641 0403
Passcode: 745379
Find your local number: https://zoom.us/u/adtpQBjgT9

**Comment by eteridvalishvili** [comment]
Eteri / FINOS

**Comment by chrisisla** [comment]
Chris Rayner / ISLA

**Comment by mgratacos** [comment]
Marc Gratacos / TradeHeader

**Comment by manel-martos** [comment]
Manuel Martos / TradeHeader

**Comment by minesh-s-patel** [comment]
@minesh-s-patel / REGnosys

**Comment by martincwwalker** [comment]
Martin Walker / FIS

**Comment by llynhiavu** [comment]
Lyteck Lynhiavu / ISDA
